### ISSUE TITLE
Problem creating releases

### ISSUE THREAD

**Issue by bwhitehead0** [bwhitehead0/get_job_id#1]
Creating releases ends in HTTP 500 error. Support request sent to GitHub.

Must use action by calling `@main`:

```yaml
      - name: Get Build job ID (action)
        uses: bwhitehead0/get_job_id@main
        id: get_build_job_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
